In [3]:
"hello"

'hello'

In [1]:
import pandas as pd   # type: ignore

In [2]:
pd.__version__

'2.2.3'

key Data Structures
Series = one list
DataFrame = Full table

Panda Series

Create Series

sales = pd.series([2,3,5])

In [3]:
sales = pd.Series([2,3,5,4,8,7])

In [26]:
sales

0    2
1    3
2    5
3    4
4    8
5    7
dtype: int64

In [15]:
sales[2]

np.int64(5)

In [27]:
sales[0:2]

0    2
1    3
dtype: int64

In [28]:
sales.index

RangeIndex(start=0, stop=6, step=1)

In [29]:
sales.values

array([2, 3, 5, 4, 8, 7])

In [19]:
sales.dtype

dtype('int64')

In [30]:
sales.head

<bound method NDFrame.head of 0    2
1    3
2    5
3    4
4    8
5    7
dtype: int64>

In [31]:
sales.tail

<bound method NDFrame.tail of 0    2
1    3
2    5
3    4
4    8
5    7
dtype: int64>

In [33]:
sales.sort_values(ascending=True)

0    2
1    3
3    4
2    5
5    7
4    8
dtype: int64

In [34]:
sales.isnull

<bound method Series.isnull of 0    2
1    3
2    5
3    4
4    8
5    7
dtype: int64>

In [4]:
sales.head(2)

0    2
1    3
dtype: int64

In [6]:
sales.count()

np.int64(6)

In [7]:
sales.isnull()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [8]:
sales.notnull()

0    True
1    True
2    True
3    True
4    True
5    True
dtype: bool

In [9]:
sales + 1

0    3
1    4
2    6
3    5
4    9
5    8
dtype: int64

In [10]:
sales

0    2
1    3
2    5
3    4
4    8
5    7
dtype: int64

In [11]:
sales *2

0     4
1     6
2    10
3     8
4    16
5    14
dtype: int64